export {default as Arrow} from './arrow.svg'
export {default as Config} from './config.svg'
export {default as Next} from './next2.svg'
export {default as Pause} from './pause2.svg'
export {default as Play} from './play2.svg'
export {default as Stop} from './stop2.svg'